# Stage 1: Build the React application
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /usr/src/react-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve the React application using Nginx
FROM nginx:alpine

# Copy the built React files from the build stage to the Nginx HTML directory
COPY --from=build /usr/src/react-app/build /usr/share/nginx/html

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port Nginx will run on
EXPOSE 8080

# Define the command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
