# Stage 1: Build the React application
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /usr/src/react-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the React application
RUN npm run build
